server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;

        # FILTRO MAESTRO: Busca cualquier atributo integrity y lo vacía para que el navegador no lo valide
        sub_filter_types text/html text/javascript;
        sub_filter 'integrity="sha' 'data-removed-integrity="sha';
        sub_filter "integrity='sha" "data-removed-integrity='sha";
        sub_filter_once off; # Aplica el cambio a TODO el documento, no solo a la primera coincidencia
    }
}
