server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;

        sub_filter_types text/html text/javascript;
        sub_filter 'integrity="sha' 'data-removed-integrity="sha';
        sub_filter "integrity='sha" "data-removed-integrity='sha";
        sub_filter_once off;
    }
}
